### ISSUE TITLE
Typo / Salah Perhitungan di point D

### ISSUE THREAD

**Issue by razorcombro** [ibnux/Skema-eKTP#1]
# | keterangan
-- | --
31 | DKI JAKARTA
74 | KOTA JAKARTA BARAT
09 | JAGAKARSA
61 | Tanggal lahir, jika wanita dikurangi 40, 61-40 = 21 ini typo gan seharus nya di tambah kalo di liat sesuai KTP

**Comment by ibnux** [comment]
@razorcombro bukan typo, karena yang ditambah ada disisi kiri yang 61, penjelasannya untuk mendapatkan tanggal asli

mungkin kurang jelas penjelasannya  :D

**Comment by razorcombro** [comment]
Siap om suwun...
